### ISSUE TITLE
Conflicting license and message

### ISSUE THREAD

**Issue by ghost** [Jan4V/hlnonvr#1]
In your code, at `hlnonvr/src/dllmain.cpp` you say the following at line 15:
``` c
const char* message = "Created by Jan4V, do not redistribute without prior permission.";
```
While also publishing the entire repository licensed under GPL-3.0 as specified in `hlnonvr/LICENSE`.

This is conflicting, because the GPL-3.0 license allows redistribution without such a restriction.
Please clarify this.

**Comment by substanc3-dev** [comment]
Apologies, that applied to v0.1, I relicensed it to GPLv3 for this release.
I have corrected this in both the codebase and the release build.
