### ISSUE TITLE
Using both -game and -vr

### ISSUE THREAD

**Issue by CarrotMist** [Jan4V/hlnonvr#4]
Whenever I run hlnonvr using both the -vr and -game custom parameters, I get the mongoose steam vr time out error.

I have validated both steamVR and HL:A.

-vr works by itself, as well as -game custom, they just do not work when both used, or I am doing something wrong. 

Target: `"E:\SteamLibrary\steamapps\common\Half-Life Alyx\game\bin\win64\hlnonvr.exe" -vr -game custom`

![Mongoose Error](https://i.imgur.com/4rpMY1S.png)

**Comment by substanc3-dev** [comment]
Make sure your "Mod" and "Write" are set to "hlvr" in your gameinfo.gi

**Comment by CarrotMist** [comment]
> Make sure your "Mod" and "Write" are set to "hlvr" in your gameinfo.gi

Those are set correctly. I fixed the probably by copying the webui folder from hlvr into my custom game.
